# Definição de variáveis de autenticação sensíveis por manifesto
##################################################
# RECOMENDA-SE DEFINIR OS SECRETS SEM O MANIFEST
#
# kubectl create secret generic auth-secrets \
#   --namespace=toggle \
#   --from-literal=MASTER_KEY='CHAVE_MASTER' \
#   --annotation=description="Variáveis de autenticação sensíveis"
##################################################
apiVersion: external-secrets.io/v1
#apiVersion: v1
kind: ExternalSecret
#kind: Secret
metadata:
  name: auth-secrets
  namespace: toggle
  annotations:
    description: "Variáveis de autenticação sensíveis"
#type: Opaque

# Chave codificada com Base64 -> echo -n 'valor' | base64
#data:
#  MASTER_KEY:

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: MASTER_KEY
      remoteRef:
        key: fiap-toggle/master_key   # Nome do secret no AWS Secrets Manager
        property: password            # Campo JSON do secret