# Definição de variáveis de autenticação sensíveis por manifesto
##################################################
# RECOMENDA-SE DEFINIR OS SECRETS SEM O MANIFEST
#
# kubectl create secret generic auth-secrets \
#   --namespace=toggle \
#   --from-literal=DATABASE_URL='postgres://USER:PASS@URL:PORT/DB' \
#   --annotation=description="Variáveis de autenticação sensíveis"
##################################################
apiVersion: external-secrets.io/v1
#apiVersion: v1
kind: ExternalSecret
#kind: Secret
metadata:
  name: db-secrets
  namespace: toggle
  annotations:
    description: "Variáveis de autenticação de DB"
#type: Opaque

# Chave codificada com Base64 -> echo -n 'valor' | base64
#data:
  # String de conexão do banco de dados PostgreSQL
#  DATABASE_URL:

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: db-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: fiap-toggle/rds   # Nome do secret no AWS Secrets Manager
        property: db_url       # Campo JSON do secret