# Definição de variáveis de configuração não-sensíveis
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: toggle
  annotations:
    description: "Variáveis de configuração não-sensíveis"
data:
  # Porta em que o analytics-service receberá requisições
  PORT: "8005"
  # Nome da tabela DynamoDB
  AWS_DYNAMODB_TABLE: "fiap-toggle-dynamo-table"
  # Região da fila SQS e DynamoDB
  AWS_REGION: "us-east-1"